src/java/beans/Administrator.java
package beans;

public class Administrator extends User{ 
    public Administrator() {
        super();
    }
}

src/java/beans/Customer.java
package beans;

public class Customer extends User {
    public Customer() {
        super();
    }
}

src/java/beans/Film.java
package beans;

import java.io.Serializable;
import java.sql.Date;

public class Film implements Serializable {

    private int filmId;
    private String title;
    private String description;
    private String classification;
    private int runtime;
    private Date releaseDate;
    
    public Film() {
        
        filmId = 0;
        title = "";
        description = "";
        classification = "";
        runtime = 0;
        releaseDate = null;
    }
    
    public int getFilmId() {
        return filmId;
    }

    public void setFilmId(int filmId) {
        this.filmId = filmId;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }
    
    public String getClassification() {
        return classification;
    }
    
    public void setClassification(String classification) {
        this.classification = classification;
    }
    
    public int getRuntime() {
        return runtime;
    }
    
    public void setRuntime(int runtime) {
        this.runtime = runtime;
    }

    public Date getReleaseDate() {
        return releaseDate;
    }

    public void setReleaseDate(Date releaseDate) {
        this.releaseDate = releaseDate;
    }
    
    @Override
    public String toString() {
        return "FilmID:"+filmId+" Title:"+title+" Description:"+description;
    }
}

src/java/beans/Session.java
package beans;

import java.io.Serializable;
import java.sql.Date;
import java.sql.Time;

public class Session implements Serializable{
    
    private int sessionId;
    private int filmId;
    private int screenId;
    private String screenName;
    private String cinemaName;
    private Date date;
    private Time time;
    
    public Session() {
        
        sessionId = 0;
        filmId = 0;
        screenId = 0;
        date = null;
        time = null;
        screenName = "";
        cinemaName = "";
    }

    public int getSessionId() {
        return sessionId;
    }

    public void setSessionId(int sessionId) {
        this.sessionId = sessionId;
    }

    public int getFilmId() {
        return filmId;
    }

    public void setFilmId(int filmId) {
        this.filmId = filmId;
    }

    public int getScreenId() {
        return screenId;
    }

    public void setScreenId(int screenId) {
        this.screenId = screenId;
    }
    
    public String getScreenName() {
        return screenName;
    }
    
    public void setScreenName(String screenName) {
        this.screenName = screenName;
    }
    
    public String getCinemaName() {
        return cinemaName;
    }
    
    public void setCinemaName(String cinemaName) {
        this.cinemaName = cinemaName;
    }

    public Date getDate() {
        return date;
    }

    public void setDate(Date date) {
        this.date = date;
    }

    public Time getTime() {
        return time;
    }

    public void setTime(Time time) {
        this.time = time;
    }
    
    @Override
    public String toString() {
        return "";
    }
}

src/java/beans/Ticket.java
package beans;

import java.io.Serializable;
import java.sql.Date;
import java.sql.Time;

public class Ticket implements Serializable{
    
    private int ticketId;
    private String customerUsername;
    private int sessionId;
    private String filmTitle;
    private String cinemaName;
    private String screenName;
    private Date dateOfSession;
    private Time sessionStartTime;
    
    public Ticket() {
        
        ticketId = 0;
        customerUsername = "";
        sessionId = 0;
        filmTitle = "";
        cinemaName = "";
        screenName = "";
        dateOfSession = null;
        sessionStartTime = null;
    }

    public int getTicketId() {
        return ticketId;
    }

    public void setTicketId(int ticketId) {
        this.ticketId = ticketId;
    }

    public String getCustomerUsername() {
        return customerUsername;
    }

    public void setCustomerUsername(String customerUsername) {
        this.customerUsername = customerUsername;
    }

    public int getSessionId() {
        return sessionId;
    }

    public void setSessionId(int sessionId) {
        this.sessionId = sessionId;
    }
    
    public String getFilmTitle() {
        return filmTitle;
    }
    
    public void setFilmTitle(String filmTitle) {
        this.filmTitle = filmTitle;
    }
    
    public String getCinemaName() {
        return cinemaName;
    }
    
    public void setCinemaName(String cinemaName) {
        this.cinemaName = cinemaName;
    }
    
    public String getScreenName() {
        return screenName;
    }
    
    public void setScreenName(String screenName) {
        this.screenName = screenName;
    }
    
    public Date getDateOfSession() {
        return dateOfSession;
    }
    
    public void setDateOfSession(Date dateOfSession) {
        this.dateOfSession = dateOfSession;
    }
    
    public Time getSessionStartTime() {
        return sessionStartTime;
    }
    
    public void setSessionStartTime(Time sessionStartTime) {
        this.sessionStartTime = sessionStartTime;
    }
    
    @Override
    public String toString() {
        return "";
    }
}

src/java/beans/User.java
package beans;

import java.io.Serializable;

public class User implements Serializable{
    
    protected String username;
    protected String password;
    
    public User() {
        username = "";
        password = "";
    }
    
    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }
    
    @Override
    public String toString() {
        return "";
    }  
}

src/java/commands/Controller.java
package commands;

import managed_Beans.*;

public class Controller {

    public String executeCommand(String userCommand, BackingBean managedBean) {
        Command command = CommandFactory.createCommand(userCommand, managedBean);
        return command.execute();
    }
}

src/java/managed_Beans/BackingBean.java
package managed_Beans;

import beans.Film;
import beans.Session;
import java.util.ArrayList;

public abstract class BackingBean {
    
    public final static String GET_ALL_FILMS = "GET_ALL_FILMS";
    public final static String GET_FILM_SESSIONS = "GET_FILM_SESSIONS";
    public final static String VALIDATE_CREDENTIALS = "VALIDATE_CREDENTIALS";
    
    String errorMessage;
    String username = null;
    String password = null;
    
    ArrayList<Film> films;
    ArrayList<Session> sessions;
    
      
    public String getUsername() {
        return username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    
    public String getPassword() {
        return password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    
    public String getErrorMessage() {
        return errorMessage;
    }
    
    public void setErrorMessage(String errorMessage) {
        this.errorMessage = errorMessage;
    }
    
    public abstract ArrayList<Film> getFilms();
    
    public abstract void setFilms(ArrayList<Film> films);
    
    public abstract void setSessions(ArrayList<Session> session);
    
    public abstract Film getFilmToDisplay();    
}

web/administrator/addSession.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <h:head>
        <title>Cinema - Add Session</title>
    </h:head>
    <h:body>
        <ui:composition template="administratorBanner.xhtml">
            <ui:define name="content">
                <h:panelGrid columns="2" border="1" rowClasses="filmSubTableRow" class="subTable" columnClasses="col1,col2">              
                    <h:graphicImage library="images" name="#{administratorBB.filmToDisplay.filmId}.jpg"
                                    alt="Film_Poster"/>
                    <h:panelGroup>
                        <h:outputText value="#{administratorBB.filmToDisplay.title}"/>
                        <p><h:outputText value="#{administratorBB.filmToDisplay.description}" class="filmDescription" /></p>
                        <p><h:outputText value="Rating: #{administratorBB.filmToDisplay.classification}"/></p>
                        <p><h:outputText value="Runtime: #{administratorBB.filmToDisplay.runtime}mins"/></p>
                        <p>
                            <h:outputText value="Release Date: "/>
                            <h:outputText value="#{administratorBB.filmToDisplay.releaseDate}"
                                          converter="dateConverter"/>
                        </p>
                    </h:panelGroup>               
                </h:panelGrid>
                
                <h1><h:outputText value="Create new session for film"/></h1>
                
                <h:form>
                    <h:panelGrid columns="3">
                        
                        <h:outputText value="Screen:"/>
                        <h:selectOneMenu id="screenList"
                                         value="#{administratorBB.sessionToCreate.screenId}"
                                         required="true"
                                         requiredMessage="Please choose a screen">
                            <f:selectItem itemValue="1" itemLabel="Broad Street - A"/>
                            <f:selectItem itemValue="2" itemLabel="Broad Street - B"/>
                            <f:selectItem itemValue="3" itemLabel="Star City - A"/>
                            <f:selectItem itemValue="4" itemLabel="Star City - B"/>
                            <f:selectItem itemValue="5" itemLabel="Touchwood - A"/>
                            <f:selectItem itemValue="6" itemLabel="Touchwood - VIP-A"/>
                        
                        </h:selectOneMenu>
                        <h:message class="errorMessage" for="screenList"/>

                        <h:outputText value="Date:"/>
                        <h:inputText id="date"
                                     title="Date of session:"
                                     value="#{administratorBB.sessionToCreate.date}"
                                     size="10"
                                     maxlength="10"
                                     required="true"
                                     converter="dateConverter"
                                     requiredMessage="Please enter a date for the session">
                        </h:inputText>
                        <h:message class="errorMessage" for="date"/>

                        <h:outputText value="Start Time:"/>
                        <h:inputText id="startTime"
                                     title="Session start time:"
                                     value="#{administratorBB.sessionToCreate.time}"
                                     size="10"
                                     maxlength="5"
                                     required="true"
                                     requiredMessage="Please enter a start time"
                                     converter="timeConverter">
                        </h:inputText>
                        <h:message class="errorMessage" for="startTime"/>
                        <h:panelGroup>
                            <h:commandButton value="OK" action="#{administratorBB.addSession()}"/>
                            <h:commandButton value="Cancel" immediate="true" action="viewEditSessions.xhtml"/>
                        </h:panelGroup>
                    </h:panelGrid>
                </h:form>
            </ui:define>
        </ui:composition>
    </h:body>
</html>

web/administrator/deleteSession.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <h:head>
        <title>Cinema - Administrator</title>
    </h:head>
    <h:body>
        <ui:composition template="administratorBanner.xhtml">
            <ui:define name="content">
                <h2><h:outputText value="WARNING: You are about to delete this session."/></h2>
                <p><h:outputText value="Deleting this session will remove all assosiated Tickets"/></p>
                <h:form>
                    <h:commandButton type="submit" value="Delete Session" action="#{administratorBB.removeSession()}"/>
                    <h:commandButton type="submit" value="Cancel" immediate="true" action="viewEditSessions.xhtml"/>
                </h:form>
            </ui:define>
        </ui:composition>
    </h:body>
</html>

web/administrator/updateSessionDetails.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <h:head>
        <title>Cinema - Edit Session</title>
    </h:head>
    <h:body>
        <ui:composition template="administratorBanner.xhtml">
            <ui:define name="content">
                <h:panelGrid columns="2" border="1" rowClasses="filmSubTableRow" class="subTable" columnClasses="col1,col2">              
                    <h:graphicImage library="images" name="#{administratorBB.filmToDisplay.filmId}.jpg"
                                    alt="Film_Poster"/>
                    <h:panelGroup>
                        <h:outputText value="#{administratorBB.filmToDisplay.title}"/>
                        <p><h:outputText value="#{administratorBB.filmToDisplay.description}" class="filmDescription" /></p>
                        <p><h:outputText value="Rating: #{administratorBB.filmToDisplay.classification}"/></p>
                        <p><h:outputText value="Runtime: #{administratorBB.filmToDisplay.runtime}mins"/></p>
                        <p>
                            <h:outputText value="Release Date: "/>
                            <h:outputText value="#{administratorBB.filmToDisplay.releaseDate}"
                                          converter="dateConverter"/>
                        </p>
                    </h:panelGroup>               
                </h:panelGrid>
                
                <h1><h:outputText value="Update session details"/></h1>
                
                <h:form>
                    <h:panelGrid columns="3">
                        <h:outputText value="Session ID:"/>
                        <h:inputText id="sessionId"
                                     disabled="true"
                                     title="ID of session:"
                                     value="#{administratorBB.sessionToUpdate.sessionId}"
                                     size="10"
                                     maxlength="3"
                                     required="true"
                                     requiredMessage="Please enter a session ID."
                                     converterMessage="Error: Session ID has to be a number."
                                     validatorMessage="Session ID is already in use, please use a differnt ID."
                                     >

                        </h:inputText>
                        <h:message class="errorMessage" for="sessionId"/>

                        <h:outputText value="Screen:"/>
                        <h:selectOneMenu id="screenList"
                                         value="#{administratorBB.sessionToUpdate.screenId}"
                                         required="true"
                                         requiredMessage="Please choose a screen">
                            <f:selectItem itemValue="1" itemLabel="Broad Street - A"/>
                            <f:selectItem itemValue="2" itemLabel="Broad Street - B"/>
                            <f:selectItem itemValue="3" itemLabel="Star City - A"/>
                            <f:selectItem itemValue="4" itemLabel="Star City - B"/>
                            <f:selectItem itemValue="5" itemLabel="Touchwood - A"/>
                            <f:selectItem itemValue="6" itemLabel="Touchwood - VIP-A"/>
                        
                        </h:selectOneMenu>
                        <h:message class="errorMessage" for="screenList"/>

                        <h:outputText value="Date of Session:"/>
                        <h:inputText id="sessionDate"
                                     title="Date of Session:"
                                     value="#{administratorBB.sessionToUpdate.date}"
                                     size="10"
                                     maxlength="10"
                                     required="true"
                                     converter="dateConverter"
                                     requiredMessage="Please enter a date for this session.">
                        </h:inputText>
                        <h:message class="errorMessage" for="sessionDate"/>

                        <h:outputText value="Start Time:"/>
                        <h:inputText id="startTime"
                                     title="Session start time."
                                     value="#{administratorBB.sessionToUpdate.time}"
                                     size="10"
                                     maxlength="5"
                                     required="true"
                                     requiredMessage="Please enter the start time."
                                     converter="timeConverter">
                        </h:inputText>
                        <h:message class="errorMessage" for="startTime"/>

                        <h:panelGroup>
                            <h:commandButton value="OK" action="#{administratorBB.modifySessionDetails()}"/>
                            <h:commandButton value="Cancel" immediate="true" action="viewEditSessions.xhtml"/>
                        </h:panelGroup>
                    </h:panelGrid>
                </h:form>
            </ui:define>
        </ui:composition>
    </h:body>
</html>

web/administrator/viewEditSessions.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <h:head>
        <title>Cinema - Administrator</title>
    </h:head>
    <h:body>
        <ui:composition template="administratorBanner.xhtml">
            <ui:define name="content">
                <h:panelGrid columns="2" border="1" rowClasses="filmSubTableRow" class="subTable" columnClasses="col1,col2">              
                    <h:graphicImage library="images" name="#{administratorBB.filmToDisplay.filmId}.jpg"
                                    alt="Film_Poster"/>
                    <h:panelGroup>
                        <h:outputText value="#{administratorBB.filmToDisplay.title}"/>
                        <p><h:outputText value="#{administratorBB.filmToDisplay.description}" class="filmDescription" /></p>
                        <p><h:outputText value="Rating: #{administratorBB.filmToDisplay.classification}"/></p>
                        <p><h:outputText value="Runtime: #{administratorBB.filmToDisplay.runtime}mins"/></p>
                        <p>
                            <h:outputText value="Release Date: "/>
                            <h:outputText value="#{administratorBB.filmToDisplay.releaseDate}"
                                          converter="dateConverter"/>
                        </p>
                    </h:panelGroup>               
                </h:panelGrid>

                <h2><h:outputText value="Available Sessions"/></h2>

                <h:dataTable value="#{administratorBB.sessions}"
                             var="filmSession"
                             styleClass="filmTable"
                             headerClass="filmTableHeader"
                             rowClasses="filmTableOddRow,filmTableEvenRow">
                    
                    <h:column>
                        <f:facet name="header">
                            <h:outputText value="Session ID"/>
                        </f:facet>
                        <h:outputText value="#{filmSession.sessionId}"/>
                    </h:column>
                    
                    <h:column>
                        <f:facet name="header">
                            <h:outputText value="Date"/>
                        </f:facet>
                        <h:outputText value="#{filmSession.date}"
                                      converter="dateConverter"/>
                    </h:column>

                    <h:column>
                        <f:facet name="header">
                            <h:outputText value="Cinema"/>
                        </f:facet>
                        <h:outputText value="#{filmSession.cinemaName}"/>
                    </h:column>

                    <h:column>
                        <f:facet name="header">
                            <h:outputText value="Screen"/>
                        </f:facet>
                        <h:outputText value="#{filmSession.screenName}"/>
                    </h:column>

                    <h:column>
                        <f:facet name="header">
                            <h:outputText value="Start Time"/>
                        </f:facet>
                        <h:outputText value="#{filmSession.time}"
                                      converter="timeConverter"/>
                    </h:column>

                    <h:column>
                        <f:facet name="header">
                            <h:form><h:commandButton type="submit" value="Add Session" action="#{administratorBB.navigateToCreateSession()}"/></h:form>
                        </f:facet>

                        <h:form>               
                            <h:panelGroup>
                                <h:commandButton type="submit" value="Update" action="#{administratorBB.navigateToUpdateSession(filmSession)}"/>
                                <h:commandButton type="submit" value="Delete" action="#{administratorBB.navigateToDeleteSession(filmSession)}"/>
                            </h:panelGroup>
                        </h:form>
                    </h:column>
                </h:dataTable>
                <p>
                    <h:form>
                        <h:commandButton value="Back to Currently Showing" action="adminHome.xhtml"/>
                    </h:form>
                </p>                
            </ui:define>
        </ui:composition>
    </h:body>
</html>

web/bookTicket.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <h:head>
        <title>View Sessions</title>
    </h:head>
    <h:body>
        <ui:composition template="/customerBanner.xhtml">
            <ui:define name="content">              
                <h:panelGrid columns="2" border="1" rowClasses="filmSubTableRow" class="subTable" columnClasses="col1,col2">              
                    <h:graphicImage library="images" name="#{customerBB.filmToDisplay.filmId}.jpg"
                                    alt="Film_Poster"/>
                    <h:panelGroup>
                        <h:outputText value="#{customerBB.filmToDisplay.title}"/>
                        <p><h:outputText value="#{customerBB.filmToDisplay.description}" class="filmDescription" /></p>
                        <p><h:outputText value="Rating: #{customerBB.filmToDisplay.classification}"/></p>
                        <p><h:outputText value="Runtime: #{customerBB.filmToDisplay.runtime}mins"/></p>
                        <p>
                            <h:outputText value="Release Date: "/>
                            <h:outputText value="#{customerBB.filmToDisplay.releaseDate}"
                                          converter="dateConverter"/>
                        </p>
                    </h:panelGroup>               
                </h:panelGrid>
                
                <h2><h:outputText value="Confirm details and book tickets"/></h2>
                
                <h:panelGrid columns="2">
                    <h:outputText value="Cinema:"/>
                    <h:outputText value="#{customerBB.sessionToDisplay.cinemaName}"/>
                    
                    <h:outputText value="Screen:"/>
                    <h:outputText value="#{customerBB.sessionToDisplay.screenName}"/>
                    
                    <h:outputText value="Date:"/>
                    <h:outputText value="#{customerBB.sessionToDisplay.date}"
                                  converter="dateConverter"/>
                    
                    <h:outputText value="Start Time:"/>
                    <h:outputText value="#{customerBB.sessionToDisplay.time}" 
                                 converter="timeConverter"/>                                       
                </h:panelGrid>

                <h:form>
                    <p>
                        <h:outputText value="Number of tickets:"/>
                        <h:inputText value="#{customerBB.numberOfTicketsToCreate}"
                                     required="true"
                                     size="2"
                                     maxlength="1"
                                     title="Number of tickets to book:"
                                     requiredMessage="Please state how many tickets you wish to book."
                                     converterMessage="Error: Number of tickets has to be a number."
                                     id="ticketNumberInput"
                                     validator="inputValidator">
                        </h:inputText>
                        <h:message for="ticketNumberInput"/>
                    </p>
                    
                    <h:commandButton value="Book Tickets" action="#{customerBB.bookTicket()}"/>
                    <h:commandButton value="Cancel" action="filmSessions.xhtml" immediate="true"/>
                </h:form>
            </ui:define>
        </ui:composition>
    </h:body>
</html>

web/filmSessions.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <h:head>
        <title>View Sessions</title>
    </h:head>
    <h:body>
        <ui:composition template="/customerBanner.xhtml">
            <ui:define name="content">
                
        <h:panelGrid columns="2" border="1" rowClasses="filmSubTableRow" class="subTable" columnClasses="col1,col2">              
            <h:graphicImage library="images" name="#{customerBB.filmToDisplay.filmId}.jpg"
                            alt="Film_Poster"/>
            <h:panelGroup>
                <h:outputText value="#{customerBB.filmToDisplay.title}"/>
                <p><h:outputText value="#{customerBB.filmToDisplay.description}" class="filmDescription" /></p>
                <p><h:outputText value="Rating: #{customerBB.filmToDisplay.classification}"/></p>
                <p><h:outputText value="Runtime: #{customerBB.filmToDisplay.runtime}mins"/></p>
                <p>
                    <h:outputText value="Release Date: "/>
                    <h:outputText value="#{customerBB.filmToDisplay.releaseDate}"
                                  converter="dateConverter"/>
                </p>
            </h:panelGroup>               
        </h:panelGrid>
        
        <h2><h:outputText value="Available Sessions"/></h2>
        
        <h:dataTable value="#{customerBB.sessions}"
                     var="filmSession"
                     styleClass="filmTable"
                     headerClass="filmTableHeader"
                     rowClasses="filmTableOddRow,filmTableEvenRow">
            
            <h:column>
                <f:facet name="header">
                    <h:outputText value="Date"/>
                </f:facet>
                <h:outputText value="#{filmSession.date}"
                              converter="dateConverter"/>
            </h:column>
                     
            <h:column>
                <f:facet name="header">
                    <h:outputText value="Cinema"/>
                </f:facet>
                <h:outputText value="#{filmSession.cinemaName}"/>
            </h:column>
            
            <h:column>
                <f:facet name="header">
                    <h:outputText value="Screen"/>
                </f:facet>
                <h:outputText value="#{filmSession.screenName}"/>
            </h:column>
            
            <h:column>
                <f:facet name="header">
                    <h:outputText value="Start Time"/>
                </f:facet>
                <h:outputText value="#{filmSession.time}"
                              converter="timeConverter"/>
            </h:column>
            
            <h:column>                
                <h:form>               
                    <h:panelGroup>
                        <h:commandButton type="submit" value="Book Ticket" action="#{customerBB.navigateToBookTicket(filmSession)}" disabled="#{!customerBB.isLoggedIn()}"/>
                    </h:panelGroup>
                </h:form>
            </h:column>
        </h:dataTable>
        
        <p>
            <h:form>
                <h:commandButton value="Back to Currently Showing" action="index.xhtml"/>
            </h:form>
        </p>
            </ui:define>
        </ui:composition>
    </h:body>
</html>